# train_dir:
# val_dir:
# train_labels_json:
# val_labels_json:
# output_dir:
# group:
# model_name:
# model_path:
# model_suffix:
# train_samples:
# val_samples:

loss: categorical_crossentropy
optimizer: Adadelta
# optimizer_parameters:

metrices:
  - accuracy

network_parameters:
  base_network: mobilenet_v2
  out_filters: 0
  dropout: 0
  classes: 3
  activation: softmax

epochs: 100
target_height: 360
target_width: 640
channels: 3
train_class_counts:
  city street: 10
  highway: 10
  tunnel: 10
val_class_counts:
  city street: 10
  highway: 10
  tunnel: 10

train_gen:
  width_shift_range: 0
  height_shift_range: 0
  shear_range: 0
  zoom_range: 0
  horizontal_flip: false

flow:
  class_mode: categorical
  batch_size: 16
  shuffle: true
  interpolation: nearest

class_blacklist:
  - gas stations
  - parking lot
  - undefined
  - skip

weights_type: frequency